name: Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyink
          pip install "black[jupyter]"

      - name: Check Code Style
        run: |
          ci/code_style_check.sh
